/*    ==ScriptingParameters==

    SourceServerVersion : SQL Server 2017 (14.0.1000)
    SourceDatabaseEngineEdition : Microsoft SQL Server Enterprise Edition
    SourceDatabaseEngineType : SQL Server independiente

    TargetServerVersion : SQL Server 2017
    TargetDatabaseEngineEdition : Microsoft SQL Server Enterprise Edition
    TargetDatabaseEngineType : SQL Server independiente
*/

USE [master]
GO

/****** Object:  Database [SMP_ACT20WAR]    Script Date: 04/12/2017 0:04:59 ******/
CREATE DATABASE [SMP_ACT20WAR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SMP_ACT20WAR', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SMP_ACT20WAR.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SMP_ACT20WAR_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SMP_ACT20WAR_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SMP_ACT20WAR] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SMP_ACT20WAR].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SMP_ACT20WAR] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET ARITHABORT OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SMP_ACT20WAR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SMP_ACT20WAR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SMP_ACT20WAR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SMP_ACT20WAR] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET RECOVERY FULL 
GO

ALTER DATABASE [SMP_ACT20WAR] SET  MULTI_USER 
GO

ALTER DATABASE [SMP_ACT20WAR] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SMP_ACT20WAR] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SMP_ACT20WAR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SMP_ACT20WAR] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SMP_ACT20WAR] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SMP_ACT20WAR] SET QUERY_STORE = OFF
GO

USE [SMP_ACT20WAR]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SMP_ACT20WAR] SET  READ_WRITE 
GO

